# Generated by Django 3.1.7 on 2021-03-01 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputCoords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Input here you data:')),
                ('task', models.TextField(verbose_name='Координаты в любом виде')),
            ],
        ),
    ]
